// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1kv2Iw6hRh1GGO18E6OxDhDTrPv3iCVw',
    appId: '1:17255807794:web:bf7f0e5f3f9a5f836eb52b',
    messagingSenderId: '17255807794',
    projectId: 'fir-db-35cd8',
    authDomain: 'fir-db-35cd8.firebaseapp.com',
    storageBucket: 'fir-db-35cd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI1Gr5TIlBLLu5UG89r4c1vsdbwacozw0',
    appId: '1:17255807794:android:c688704657b6dca36eb52b',
    messagingSenderId: '17255807794',
    projectId: 'fir-db-35cd8',
    storageBucket: 'fir-db-35cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Woc17RAwD3JOuBdQZFQbAEBvvcKFU0U',
    appId: '1:17255807794:ios:9cd834e41a5c4a986eb52b',
    messagingSenderId: '17255807794',
    projectId: 'fir-db-35cd8',
    storageBucket: 'fir-db-35cd8.appspot.com',
    iosClientId: '17255807794-1363j59jleqoh99nc9ebj8n27nal231u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseClear19',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Woc17RAwD3JOuBdQZFQbAEBvvcKFU0U',
    appId: '1:17255807794:ios:9cd834e41a5c4a986eb52b',
    messagingSenderId: '17255807794',
    projectId: 'fir-db-35cd8',
    storageBucket: 'fir-db-35cd8.appspot.com',
    iosClientId: '17255807794-1363j59jleqoh99nc9ebj8n27nal231u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseClear19',
  );
}
